name = "job-board"
main = "src/index.js"
compatibility_date = "2024-06-14"

[[kv_namespaces]]
binding = "JOBS"
id = "your-kv-namespace-id"
preview_id = "your-preview-kv-namespace-id"

[[kv_namespaces]]
binding = "APPLICATIONS"
id = "your-applications-kv-namespace-id"
preview_id = "your-applications-preview-kv-namespace-id"

[[kv_namespaces]]
binding = "EMPLOYERS"
id = "your-employers-kv-namespace-id"
preview_id = "your-employers-preview-kv-namespace-id"

[[kv_namespaces]]
binding = "NOTIFICATIONS"
id = "your-notifications-kv-namespace-id"
preview_id = "your-notifications-preview-kv-namespace-id"

[[kv_namespaces]]
binding = "ORGANIZATIONS"
id = "your-organizations-kv-namespace-id"
preview_id = "your-organizations-preview-kv-namespace-id"

[[kv_namespaces]]
binding = "COMPANIES"
id = "your-companies-kv-namespace-id"
preview_id = "your-companies-preview-kv-namespace-id"

[[kv_namespaces]]
binding = "ORGANIZATION_USERS"
id = "your-organization-users-kv-namespace-id"
preview_id = "your-organization-users-preview-kv-namespace-id"

[[kv_namespaces]]
binding = "ACTIVITY_LOG"
id = "your-activity-log-kv-namespace-id"
preview_id = "your-activity-log-preview-kv-namespace-id"

[[kv_namespaces]]
binding = "APPLICATION_COMMENTS"
id = "your-application-comments-kv-namespace-id"
preview_id = "your-application-comments-preview-kv-namespace-id"

[env.production]
vars = { ENVIRONMENT = "production" }