name = "job-board"
main = "src/index.js"
compatibility_date = "2024-06-14"

[[kv_namespaces]]
binding = "JOBS"
id = "your-kv-namespace-id"
preview_id = "your-preview-kv-namespace-id"

[[kv_namespaces]]
binding = "APPLICATIONS"
id = "your-applications-kv-namespace-id"
preview_id = "your-applications-preview-kv-namespace-id"

[env.production]
vars = { ENVIRONMENT = "production" }