# wrangler.toml - Auth Worker Configuration

name = "locum-auth-worker"
main = "src/auth.js"
compatibility_date = "2025-01-01"

# D1 Database
[[d1_databases]]
binding = "DB"
database_name = "locum_calculator"
database_id = "${CLOUDFLARE_D1_ID}" # This will be replaced with your actual D1 database ID

# Environment variables
[vars]
JWT_SECRET = "${JWT_SECRET}" # This will be replaced with your secure JWT secret

# Routes (Custom Domain setup)
routes = [
  { pattern = "api.locumtruerate.com/api/auth/*", custom_domain = true }
]