version: '3.8'

services:
  # PostgreSQL for testing
  postgres-test:
    image: postgres:15-alpine
    container_name: locumtruerate-postgres-test
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: locumtruerate_test
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"
    ports:
      - "5433:5432"
    volumes:
      - postgres_test_data:/var/lib/postgresql/data
      - ./scripts/init-test-db.sql:/docker-entrypoint-initdb.d/init-test-db.sql
    networks:
      - test-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d locumtruerate_test"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  # Redis for testing
  redis-test:
    image: redis:7-alpine
    container_name: locumtruerate-redis-test
    ports:
      - "6380:6379"
    volumes:
      - redis_test_data:/data
    networks:
      - test-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru

  # MinIO for S3-compatible storage testing
  minio-test:
    image: minio/minio:latest
    container_name: locumtruerate-minio-test
    ports:
      - "9001:9000"
      - "9091:9001"
    environment:
      MINIO_ROOT_USER: testuser
      MINIO_ROOT_PASSWORD: testpassword
    volumes:
      - minio_test_data:/data
    networks:
      - test-network
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
      start_period: 30s

  # Mailhog for email testing
  mailhog-test:
    image: mailhog/mailhog:latest
    container_name: locumtruerate-mailhog-test
    ports:
      - "1026:1025"  # SMTP
      - "8026:8025"  # Web UI
    networks:
      - test-network
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8025"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Test database initialization
  db-init:
    build:
      context: .
      dockerfile: Dockerfile.test-init
    container_name: locumtruerate-db-init
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres-test:5432/locumtruerate_test
    depends_on:
      postgres-test:
        condition: service_healthy
    networks:
      - test-network
    volumes:
      - ./packages/database/prisma:/app/prisma
      - ./packages/database/src/seed-test.ts:/app/seed-test.ts
    command: >
      sh -c "
        echo 'Waiting for database to be ready...' &&
        npx prisma migrate deploy &&
        npx prisma db push &&
        echo 'Database initialized successfully'
      "

volumes:
  postgres_test_data:
    driver: local
  redis_test_data:
    driver: local
  minio_test_data:
    driver: local

networks:
  test-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16